DROP DATABASE IF EXISTS db;
CREATE DATABASE db;

USE db;


CREATE TABLE department(
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE employee(
  id INT AUTO_INCREMENT NOT NULL,
  firstName VARCHAR(30) NOT NULL,
  lastName VARCHAR(30) NOT NULL,
  employeeRole VARCHAR(30) NOT NULL,
  managerName VARCHAR(30),
  PRIMARY KEY (id)
);
CREATE TABLE role(
  id INT AUTO_INCREMENT NOT NULL,
  roleTitle VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  departmentName VARCHAR(30),
  PRIMARY KEY (id)
);
